/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file. Run `npm run gen:api` to regenerate.
 */

export interface paths {
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions
         * @description Customer sees own; employee sees all or filtered by userId. Optional filters: dateFrom, dateTo, account (IBAN or accountNumber), amountInCents (with amountFilter LessThan|EqualTo|GreaterThan, default EqualTo). Sort via ?sort=field,dir (default timestamp,desc).
         */
        get: operations["getTransactions"];
        put?: never;
        /**
         * Execute a transaction
         * @description Transfers funds between two accounts. The from/to fields accept either an IBAN or a numeric account number.
         */
        post: operations["executeTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new customer. Account requires employee approval.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate and receive a JWT token
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customer savings and checking accounts
         * @description Returns all accounts for the authenticated user, or can be used to search for other users. Employees can view all accounts.
         */
        get: operations["listAllAccounts"];
        put?: never;
        /**
         * Approve customer and create accounts
         * @description Approves the given pending customer and creates one checking and one savings account.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one user
         * @description Returns just one user from the given ID.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Delete specific user
         * @description Deletes a specific user, archiving their account.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /**
         * Update specific user
         * @description Update values for a specific user.
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account details
         * @description Returns details for a single customer account.
         */
        get: operations["getAccountInfo"];
        put?: never;
        post?: never;
        /**
         * Close an account
         * @description Employee can close a specific account from an user.
         */
        delete: operations["closeAccount"];
        options?: never;
        head?: never;
        /**
         * Update specific savings or checking account
         * @description Updates the absolute limit, daily limit, or closed status of an account.
         */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all users
         * @description Returns all user accounts.
         */
        get: operations["getAllUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one user
         * @description Returns info on the logged in user.
         */
        get: operations["getSelfUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TransactionRequest: {
            from: string;
            to: string;
            /** Format: int64 */
            amountInCents: number;
        };
        TransactionResponse: {
            /** Format: int64 */
            transactionId: number;
            from: string;
            to: string;
            /** Format: int64 */
            amountInCents: number;
            /** Format: date-time */
            timestamp: string;
            initiatedBy: string;
        };
        RegisterRequest: {
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            password: string;
            bsn: string;
            phoneNumber: string;
        };
        UserResponse: {
            /** Format: int64 */
            userId: number;
            firstName: string;
            lastName: string;
            email: string;
            phoneNumber: string;
            bsn: string;
            /** @enum {string} */
            role: "Customer" | "Employee";
            /** Format: date-time */
            registrationDate: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
        };
        NewAccountRequest: {
            /** Format: int64 */
            userId: number;
            /** Format: int64 */
            absoluteLimitInCents?: number;
            /**
             * Format: int64
             * @default 50000
             */
            dailyLimitInCents: number;
        };
        ApiResponse: {
            message: string;
        };
        UserPatchRequest: {
            firstName?: string;
            lastName?: string;
            /** Format: email */
            email?: string;
        };
        UpdateAccountRequest: {
            /** Format: int64 */
            absoluteLimitInCents?: number;
            /** Format: int64 */
            dailyLimitInCents?: number;
            closed?: boolean;
        };
        AccountDetailResponse: {
            /** Format: int64 */
            accountId: number;
            iban?: string;
            accountType: string;
            /** Format: int64 */
            storedAmountInCents: number;
            /** Format: int64 */
            userId: number;
            /** Format: int32 */
            absoluteLimitInCents: number;
            /** Format: int32 */
            dailyLimitInCents: number;
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelUserResponse: {
            content?: components["schemas"]["UserResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelTransactionResponse: {
            content?: components["schemas"]["TransactionResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
        AccountSummaryResponse: {
            /** Format: int64 */
            accountId: number;
            iban?: string;
            ownerFirstName: string;
            ownerLastName: string;
            accountType: string;
        };
        PagedModelAccountSummaryResponse: {
            content?: components["schemas"]["AccountSummaryResponse"][];
            page?: components["schemas"]["PageMetadata"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getTransactions: {
        parameters: {
            query?: {
                userId?: number;
                dateFrom?: string;
                dateTo?: string;
                account?: string;
                amountInCents?: number;
                amountFilter?: "LessThan" | "EqualTo" | "GreaterThan";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelTransactionResponse"];
                };
            };
        };
    };
    executeTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    listAllAccounts: {
        parameters: {
            query?: {
                iban?: string;
                firstName?: string;
                lastName?: string;
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAccountSummaryResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    getAccountInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountDetailResponse"];
                };
            };
        };
    };
    closeAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountDetailResponse"];
                };
            };
        };
    };
    getAllUsers: {
        parameters: {
            query?: {
                isApproved?: boolean;
                role?: "Customer" | "Employee";
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelUserResponse"];
                };
            };
        };
    };
    getSelfUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
}
