// Generates src/types/schema.d.ts from the backend's OpenAPI spec.
// The spec URL comes from API_SPEC_URL, loaded from .env (Can be changed later to load from elsewhere if needed)
// This script is mostly here to be able to read .env for the url (package.json calls this script)
// Run with: npm run gen:api --prefix frontend
import openapiTS, { astToString } from "openapi-typescript";
import { writeFile } from "node:fs/promises";

const url = process.env.API_SPEC_URL;
if (!url) {
    console.error(
        "API_SPEC_URL is not set.\n" +
            "Create frontend/.env with, e.g.:\n" +
            "  API_SPEC_URL=http://localhost:8080/v3/api-docs",
    );
    process.exit(1);
}

const out = new URL("../src/types/schema.d.ts", import.meta.url);

const banner =
    "/**\n" +
    " * This file was auto-generated by openapi-typescript.\n" +
    " * Do not make direct changes to the file. Run `npm run gen:api` to regenerate.\n" +
    " */\n\n";

console.log(`Generating API types from ${url}`);
const ast = await openapiTS(new URL(url));
await writeFile(out, banner + astToString(ast));
console.log(`Wrote ${out.pathname}`);
